### ISSUE TITLE
Error searching songs with a search term containing double quotes

### ISSUE THREAD

**Issue by progo** [finnyb/javampd#208]
Latest version 7.3.0 under JVM 17 and kotlin.

```
        val mpd = MPD.builder().build()
        mpd.songSearcher.search(
            SongSearcher.ScopeType.ANY,
            "Music from the Film \"Motion Picture: The Movie\" The Soundtrack")
```

```
14:15:49.598 [Test worker @coroutine#1] ERROR org.bff.javampd.server.MPDSocket - Got error from command search "(album contains 'Music from the Film \\"Motion Picture: The Movie\\" The Soundtrack')"

14:15:49.603 [Test worker @coroutine#1] ERROR org.bff.javampd.server.MPDSocket - Error from: search
org.bff.javampd.server.MPDConnectionException: [5@0] {} Space expected after closing '"'
	at org.bff.javampd.server.MPDSocket.sendBytes(MPDSocket.java:235)
	at org.bff.javampd.server.MPDSocket.sendCommand(MPDSocket.java:108)
	at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:56)
	at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:39)
	at org.bff.javampd.song.MPDSongSearcher.search(MPDSongSearcher.java:80)
	at org.bff.javampd.song.MPDSongSearcher.search(MPDSongSearcher.java:48)
	at org.bff.javampd.song.MPDSongSearcher.search(MPDSongSearcher.java:36)
	at utils.mpd.MPDQueryIntegrTest$search albums by doublequoted search$1.invokeSuspend(MPDQueryIntegrTest.kt:54)

14:15:49.611 [Test worker @coroutine#1] ERROR org.bff.javampd.server.MPDSocket - 	param: (album contains 'Music from the Film "Motion Picture: The Movie" The Soundtrack')
```

Extra-escaping the query term into the form `\\\"foobar\\\"` will avoid this error, and produce a correct query with correct results. But is this a bug or a feature? Docs do not mention about needing to overly escape double quotes.

I wouldn't characterise this problem being something I fat-fingered in a string in a test. The problem came up in my actual code that roughly does this (in heavy pseudo):

```
query = "input from GUI"
songs = search_songs(query, Scope.ANY)
albums = songs.mapcat(song -> search_songs(song.album, Scope.ALBUM))
```

Thank you for reading, and big thanks for maintaining this library!

**Comment by finnyb** [comment]
Please give release 7.3.1 a try

**Comment by progo** [comment]
Perfect!
Many thanks. Speedy operation. 8)
