### ISSUE TITLE
exception since commit 8bbff6f1e0f9a781accadd610a820a22944e6519

### ISSUE THREAD

**Issue by stefanroellin** [finnyb/javampd#49]
The following program fails since commit  8bbff6f1e0f9a781accadd610a820a22944e6519, whereas it worked before:

```
package org.test;

import java.net.UnknownHostException;
import org.bff.javampd.server.MPD;

public class TestJavaMPD {
	public static void main(String[] args) {
		MPD mpd;
		try {
			mpd = new MPD.Builder().server("localhost").port(6600).build();
			System.out.println(mpd.getServerStatus().getStatus().toString());
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
	}
}
```

The following exception occurs:

```
Exception in thread "main" org.bff.javampd.server.MPDConnectionException: Unable to send command org.bff.javampd.command.MPDCommand@8eec2e4f
	at org.bff.javampd.server.MPDSocket.sendCommand(MPDSocket.java:129)
	at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:59)
	at org.bff.javampd.command.MPDCommandExecutor.sendCommand(MPDCommandExecutor.java:38)
	at org.bff.javampd.server.MPDServerStatus.getStatus(MPDServerStatus.java:75)
	at org.test.TestJavaMPD.main(TestJavaMPD.java:13)
```

**Comment by finnyb** [comment]
Sorry for the delay but this should be resolved.

Thanks,
Bill

**Comment by stefanroellin** [comment]
Thanks for the fix - it now works as expected.
