### ISSUE TITLE
getMixRampDb() throws NumberFormatException

### ISSUE THREAD

**Issue by rain0r** [finnyb/javampd#73]
In MPDServerStatus.java:

https://github.com/finnyb/javampd/blob/7a94d9f0f29965713f1eae3ce6761c757b2e18f5/src/main/java/org/bff/javampd/server/MPDServerStatus.java#L227 

The method `getMixRampDb()` is throwing NumberFormatException:

```
Caused by: java.lang.NumberFormatException: For input string: "0.000000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:652) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
	at org.bff.javampd.server.MPDServerStatus.getMixRampDb(MPDServerStatus.java:227) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
```

This should be easy to fix. Let me know if you would accept a PR for this or if it's an unusual behaviour of my setup.

**Comment by finnyb** [comment]
I'd be more than happy to accept a PR for this.  Thanks

**Comment by rain0r** [comment]
> I'd be more than happy to accept a PR for this. Thanks

Please see PR https://github.com/finnyb/javampd/pull/75
